//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAzure.SServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SServiceReference1.IWordSearchService")]
    public interface IWordSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordSearchService/Search", ReplyAction="http://tempuri.org/IWordSearchService/SearchResponse")]
        string Search(string sentence, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordSearchService/Search", ReplyAction="http://tempuri.org/IWordSearchService/SearchResponse")]
        System.Threading.Tasks.Task<string> SearchAsync(string sentence, string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordSearchServiceChannel : TestAzure.SServiceReference1.IWordSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordSearchServiceClient : System.ServiceModel.ClientBase<TestAzure.SServiceReference1.IWordSearchService>, TestAzure.SServiceReference1.IWordSearchService {
        
        public WordSearchServiceClient() {
        }
        
        public WordSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Search(string sentence, string keyword) {
            return base.Channel.Search(sentence, keyword);
        }
        
        public System.Threading.Tasks.Task<string> SearchAsync(string sentence, string keyword) {
            return base.Channel.SearchAsync(sentence, keyword);
        }
    }
}
